"""Synthetic transport contract fixture for offline Anti chunk planning."""

TRANSPORT_CASES = {
    "connect_gateway": {"status": "ready", "diagnostic": "HTTP_CONNECT", "retry": False},
    "reject_bad_url": {"status": "failed", "diagnostic": "HTTP_URL", "retry": False},
    "advertise_models": {"status": "ready", "diagnostic": "HTTP_MODELS", "retry": False},
    "reject_missing_model": {"status": "failed", "diagnostic": "HTTP_MODEL", "retry": False},
    "send_responses_request": {"status": "submitted", "diagnostic": "HTTP_REQUEST", "retry": False},
    "accept_http_200": {"status": "ready", "diagnostic": "HTTP_200", "retry": False},
    "retry_http_408": {"status": "retryable", "diagnostic": "HTTP_408", "retry": True},
    "retry_http_429": {"status": "retryable", "diagnostic": "HTTP_429", "retry": True},
    "retry_http_500": {"status": "retryable", "diagnostic": "HTTP_500", "retry": True},
    "retry_http_502": {"status": "retryable", "diagnostic": "HTTP_502", "retry": True},
    "retry_http_503": {"status": "retryable", "diagnostic": "HTTP_503", "retry": True},
    "retry_http_504": {"status": "retryable", "diagnostic": "HTTP_504", "retry": True},
    "reject_http_401": {"status": "failed", "diagnostic": "HTTP_401", "retry": False},
    "reject_http_403": {"status": "failed", "diagnostic": "HTTP_403", "retry": False},
    "reject_http_404": {"status": "failed", "diagnostic": "HTTP_404", "retry": False},
    "reject_http_422": {"status": "failed", "diagnostic": "HTTP_422", "retry": False},
    "honor_retry_after": {"status": "retryable", "diagnostic": "HTTP_RETRY_AFTER", "retry": True},
    "defer_long_retry_after": {"status": "failed", "diagnostic": "HTTP_RETRY_CAP", "retry": False},
    "defer_bad_retry_after": {"status": "failed", "diagnostic": "HTTP_RETRY_HEADER", "retry": False},
    "honor_timeout": {"status": "failed", "diagnostic": "HTTP_TIMEOUT", "retry": True},
    "honor_total_deadline": {"status": "failed", "diagnostic": "HTTP_DEADLINE", "retry": False},
    "release_account": {"status": "released", "diagnostic": "HTTP_RELEASE", "retry": False},
    "preserve_model_identity": {"status": "ready", "diagnostic": "HTTP_IDENTITY", "retry": False},
    "record_actual_provider": {"status": "ready", "diagnostic": "HTTP_PROVIDER", "retry": False},
    "reject_unadvertised_fallback": {"status": "failed", "diagnostic": "HTTP_FALLBACK_ID", "retry": False},
    "allow_never_fallback": {"status": "ready", "diagnostic": "HTTP_FALLBACK_NEVER", "retry": False},
    "record_usage": {"status": "ready", "diagnostic": "HTTP_USAGE", "retry": False},
    "record_latency": {"status": "ready", "diagnostic": "HTTP_LATENCY", "retry": False},
    "record_attempt": {"status": "ready", "diagnostic": "HTTP_ATTEMPT", "retry": False},
    "record_rotation": {"status": "ready", "diagnostic": "HTTP_ROTATION", "retry": False},
    "reject_empty_body": {"status": "failed", "diagnostic": "HTTP_EMPTY", "retry": False},
    "reject_invalid_json": {"status": "failed", "diagnostic": "HTTP_JSON", "retry": False},
    "accept_stream_events": {"status": "ready", "diagnostic": "HTTP_STREAM", "retry": False},
    "preserve_output_indexes": {"status": "ready", "diagnostic": "HTTP_INDEX", "retry": False},
    "preserve_function_call_id": {"status": "ready", "diagnostic": "HTTP_FUNCTION_ID", "retry": False},
    "reject_duplicate_done": {"status": "failed", "diagnostic": "HTTP_DONE", "retry": False},
    "accept_terminal_response": {"status": "ready", "diagnostic": "HTTP_TERMINAL", "retry": False},
    "reject_non_terminal_response": {"status": "failed", "diagnostic": "HTTP_NON_TERMINAL", "retry": False},
    "redact_authorization": {"status": "ready", "diagnostic": "HTTP_REDACT", "retry": False},
    "reject_redirect_secret": {"status": "failed", "diagnostic": "HTTP_REDIRECT", "retry": False},
    "preserve_request_correlation": {"status": "ready", "diagnostic": "HTTP_CORRELATION", "retry": False},
    "record_deadline_reason": {"status": "ready", "diagnostic": "HTTP_DEADLINE_REASON", "retry": False},
    "record_provider_error": {"status": "failed", "diagnostic": "HTTP_PROVIDER_ERROR", "retry": False},
    "preserve_primary_error": {"status": "failed", "diagnostic": "HTTP_PRIMARY_ERROR", "retry": False},
    "preserve_fallback_reason": {"status": "failed", "diagnostic": "HTTP_FALLBACK_REASON", "retry": False},
    "accept_successful_retry": {"status": "ready", "diagnostic": "HTTP_RETRY_SUCCESS", "retry": True},
    "reject_retry_after_budget": {"status": "failed", "diagnostic": "HTTP_BUDGET", "retry": False},
    "preserve_scope_status": {"status": "ready", "diagnostic": "HTTP_SCOPE", "retry": False},
    "reject_false_complete": {"status": "failed", "diagnostic": "HTTP_SCOPE", "retry": False},
    "accept_final_judge": {"status": "ready", "diagnostic": "HTTP_JUDGE", "retry": False},
    "reject_missing_judge": {"status": "failed", "diagnostic": "HTTP_JUDGE", "retry": False},
}

